# references:
# * http://www.objc.io/issue-6/travis-ci.html
# * https://github.com/supermarin/xcpretty#usage

#rvm: 1.9.3
osx_image: xcode8.2
xcode_sdk: iphonesimulator10.1
language: objective-c
# cache: cocoapods
podfile: Example/Podfile
xcode_workspace: Example/SQLDataAccess.xcworkspace
xcode_scheme: SQLDataAccess-Example
# before_install:
# - gem install cocoapods # Since Travis is not always on latest version
# - pod install --project-directory=Example
script:
- set -o pipefail && xcodebuild test "OTHER_LDFLAGS = -lsqlite3" -workspace Example/SQLDataAccess.xcworkspace -scheme SQLDataAccess-Example -sdk iphonesimulator10.1 ONLY_ACTIVE_ARCH=NO | xcpretty
- pod lib lint
